"""Original, complete transcripts of seven short working meetings (not excerpts)."""
PEOPLE = [
    ('Priya Sharma', 'priya@northstar.example'),
    ('Arjun Mehta', 'arjun@northstar.example'),
    ('Maya Chen', 'maya@northstar.example'),
    ('Daniel Brooks', 'daniel@northstar.example'),
    ('Sofia Patel', 'sofia@northstar.example'),
]

# Each turn lasts 15 seconds; chapter boundaries align with the full transcript.
MEETINGS = [
    {
        'title': 'Sprint 12 planning: meeting search', 'date': '2026-09-28T09:00:00+00:00',
        'people': [0, 1, 2], 'source': 'Google Meet',
        'chapters': ['Scope and capacity', 'Search behavior', 'Owners and next steps'],
        'overview': 'The team scoped Sprint 12 to title and transcript search, participant filters, and stable recency sorting. Export was deferred. Search will use literal matching and reset pagination when filters change.',
        'notes': 'Decision: ship search before export. Acceptance: an empty result must explain how to clear filters. Capacity: five engineering days and two design days.',
        'tasks': [(1, 'Implement title and transcript search with stable pagination'), (2, 'Prepare empty-result and filter-reset designs')],
        'turns': [
            (0, 'Thanks for joining sprint planning. We have five engineering days available this week. I want us to finish meeting search before we take on transcript export.'),
            (1, 'That fits our capacity if we keep the search contract small. I can cover title and transcript matching, participant filters, and a stable default sort by meeting date.'),
            (2, 'Design has two days available. I have a first pass for the search field and filter menu. The biggest unanswered question is what we show when nothing matches.'),
            (0, 'Let us show the current query and a clear filters button. Export moves to the next sprint. Our acceptance test should include a search with no results.'),
            (1, 'One detail for the API: percent and underscore characters should be treated literally. Otherwise a normal query can accidentally match every meeting in the database.'),
            (2, 'Agreed. Changing a filter should return people to the first page. Keeping an old page number would make the results look empty even when matches exist.'),
            (0, 'We also need participant matching by name or email. We can keep tags out of scope for now, because we have not defined a shared taxonomy.'),
            (1, 'I will implement the search endpoints and pagination tests by Wednesday. I will post the contract in our documentation so the frontend can connect without guessing.'),
            (2, 'I will finish the empty state and filter reset designs on Tuesday. I will include keyboard focus behavior for clearing the query and opening the participant menu.'),
            (0, 'Great, we have a clear scope and owners. We will review the integrated search flow on Thursday. Thanks everyone; that is all for this planning check-in.'),
        ],
    },
    {
        'title': 'Customer onboarding feedback', 'date': '2026-09-29T14:00:00+00:00',
        'people': [0, 3, 4], 'source': 'Zoom',
        'chapters': ['Customer observations', 'Proposed onboarding changes', 'Follow-up plan'],
        'overview': 'Three pilot customers struggled to find transcripts after onboarding. The team chose a sample meeting and a direct library link in the welcome email, with a follow-up usability session.',
        'notes': 'Decision: use a sample meeting instead of a longer setup tour. Measure time to first transcript. No calendar integration is required for the pilot.',
        'tasks': [(4, 'Draft a welcome email linking directly to the sample meeting'), (3, 'Schedule usability sessions with the three pilot customers')],
        'turns': [
            (3, 'I reviewed the three onboarding calls from yesterday. All three customers completed setup, but two could not find their transcripts without asking support where to click next.'),
            (0, 'Were they blocked by permissions, or was the navigation unclear? We need to separate an access problem from a discoverability problem before we change the welcome flow.'),
            (4, 'They had access. The welcome email sends them to settings, which is useful for configuration but gives them no example of what a completed meeting looks like.'),
            (3, 'Exactly. One customer expected the transcript to arrive in their email. Another opened the library, saw an empty list, and assumed the account had not been activated.'),
            (0, 'Let us provide a sample meeting in the library and link to it from the welcome email. We can introduce settings after they have seen the actual product value.'),
            (4, 'I can write a shorter email with one primary link. The sample should include multiple speakers, chapters, and assigned tasks so it demonstrates the entire review workflow.'),
            (3, 'For measurement, I suggest time from signup to first transcript view. We should also ask customers to locate an action item without giving them navigation instructions.'),
            (0, 'That sounds useful. Keep calendar integration out of this pilot; adding another setup step would make it harder to tell whether the sample meeting improves discoverability.'),
            (4, 'I will draft the email by tomorrow. Daniel will schedule sessions with the same three customers, and we will compare their completion times after the change.'),
            (3, 'I will send those invitations today and bring the observations to Friday review. We have our next steps, so I will close the feedback check-in here.'),
        ],
    },
    {
        'title': 'Transcript detail design review', 'date': '2026-09-30T10:30:00+00:00',
        'people': [0, 1, 2], 'source': 'Google Meet',
        'chapters': ['Panel layout', 'Playback and search', 'Accessibility commitments'],
        'overview': 'The detail view will use transcript and notes panels with a compact media area. Transcript clicks seek playback; transcript search preserves context. Keyboard access and visible focus are acceptance criteria.',
        'notes': 'Decision: transcript timestamps are seek targets. Search results retain speaker labels. The media area can use a placeholder in the assignment version.',
        'tasks': [(2, 'Finalize responsive transcript and notes panel layouts'), (1, 'Document playback timestamp and keyboard interaction contracts')],
        'turns': [
            (2, 'Today I want to review the transcript detail layout. The draft places the transcript on the left, notes on the right, and a compact media player above both panels.'),
            (0, 'The split looks good on a laptop. What happens on a narrow screen? We should keep the transcript readable rather than squeezing both panels into tiny columns.'),
            (2, 'On a phone, the panels become tabs beneath the player. The title and participants stay visible at the top, while the active panel takes the full available width.'),
            (1, 'I need a clear playback contract. Clicking a transcript line can seek to its start timestamp. While playback moves, we can highlight the segment containing the current time.'),
            (2, 'Yes, but auto-scroll should pause when someone manually scrolls away. We do not want playback to pull them back while they are reading an earlier part of the conversation.'),
            (0, 'For search within the transcript, keep speaker names and timestamps in the results. A highlighted word without surrounding context will make it difficult to understand the actual discussion.'),
            (1, 'The backend returns ordered segments with start and end seconds. The UI can filter locally for small transcripts, or request matching segments while preserving their original positions.'),
            (2, 'I will add visible focus styles and keyboard activation to timestamp controls. The notes tab and transcript tab will also need accessible labels and predictable focus movement.'),
            (0, 'Please include those behaviors in the acceptance criteria. We can use a placeholder player in this version, as long as seeking and the progress display are internally consistent.'),
            (1, 'I will document the interaction contract today, and Maya will finalize responsive layouts tomorrow. That settles the remaining questions. Thanks for the review; we are done.'),
        ],
    },
    {
        'title': 'API reliability and SQLite review', 'date': '2026-10-01T08:30:00+00:00',
        'people': [0, 1, 3], 'source': 'Microsoft Teams',
        'chapters': ['Data integrity', 'Transactions and indexes', 'Verification plan'],
        'overview': 'The team agreed to enable SQLite foreign keys on every connection, cascade meeting-owned content, preserve shared participants, and test migrations and rollback behavior using temporary databases.',
        'notes': 'Decision: use Alembic for schema changes. Timeline replacements are atomic. Search uses bounded pagination; no external search service is needed.',
        'tasks': [(1, 'Add cascade-delete and transaction rollback tests'), (3, 'Review migration upgrade and downgrade instructions')],
        'turns': [
            (1, 'I found an important SQLite default during the schema review. Foreign key enforcement is disabled unless we enable it on every connection, so the connection hook must set that pragma.'),
            (3, 'Good catch. If someone deletes a meeting, do we remove its transcript and summary automatically? We should avoid leaving records that can no longer be reached through the application.'),
            (0, 'Yes, meeting-owned content should cascade. Participants are different because the same person can attend several meetings. Deleting one meeting must not delete that shared person.'),
            (1, 'I will enforce speaker and assignee membership with composite foreign keys. The API will also validate those relationships so the caller gets a useful error before a constraint fails.'),
            (3, 'What about replacing a transcript? If a segment is invalid halfway through the request, we cannot leave the meeting with only part of its original conversation remaining.'),
            (1, 'We validate the entire payload before deleting anything, then replace it in one transaction. A database failure rolls back the session when the request dependency closes.'),
            (0, 'Add indexes for meeting dates, participant membership, and transcript timestamps. We can use literal text matching for this dataset; an external search service is unnecessary right now.'),
            (3, 'I will review the migration commands and test upgrade followed by downgrade on an empty temporary database. We should document that downgrade removes the application tables.'),
            (1, 'I will add cascade deletion, invalid replacement, and cross-meeting assignee tests. The test suite will use isolated SQLite files so it never touches the seeded development database.'),
            (0, 'That covers the reliability risks for the foundation. Let us finish the tests before connecting the frontend client. Thanks both; we can end the database review here.'),
        ],
    },
    {
        'title': 'Launch messaging: private beta', 'date': '2026-10-02T13:00:00+00:00',
        'people': [0, 2, 4], 'source': 'Zoom',
        'chapters': ['Positioning', 'Beta boundaries', 'Launch checklist'],
        'overview': 'Private beta messaging will emphasize reviewing meeting notes and following up on assigned tasks. The team will clearly label mocked integrations and avoid promising live transcription.',
        'notes': 'Decision: invite ten pilot teams after the review workflow passes acceptance checks. Landing copy and demo screenshots must match the implemented scope.',
        'tasks': [(4, 'Write private beta invitation copy with explicit feature boundaries'), (2, 'Capture screenshots after the review workflow is ready')],
        'turns': [
            (4, 'For the private beta invitation, I propose leading with meeting review and follow-up. Those are the workflows customers asked for, and they are easier to explain than a long feature list.'),
            (0, 'Agreed. We should say that people can browse transcripts, read summaries, and assign next steps. We must be clear that the current demo uses prepared meeting data.'),
            (2, 'The screenshots should show a complete meeting with a readable transcript and two action items. Empty panels would make the invitation feel disconnected from the actual review experience.'),
            (4, 'Should I mention integrations? A few pilot teams use Zoom, but we are not implementing a bot that joins calls or synchronizes their calendars in this release.'),
            (0, 'Mention them only as future placeholders. Do not promise live transcription. We can invite teams to evaluate the review workflow using sample conversations before discussing recording integrations.'),
            (2, 'I will mark placeholder settings clearly in the design. The main library and detail screens should still feel complete, so customers can understand what they can use immediately.'),
            (4, 'My draft will have a single invitation link and a short explanation of the beta scope. I would like to start with ten teams so support can collect detailed feedback.'),
            (0, 'Ten is reasonable after acceptance checks pass. Ask each team to review one meeting and complete an action item, then report whether the transcript and summary agree.'),
            (2, 'I will capture screenshots once the workflow is ready. Sofia can use those in the invitation, and we can review the wording together before sending anything externally.'),
            (4, 'I will prepare the copy for internal review by Monday. We have the audience, scope, and assets settled. Thanks for the input; that finishes our launch messaging discussion.'),
        ],
    },
    {
        'title': 'Incident follow-up: duplicate action items', 'date': '2026-10-05T11:00:00+00:00',
        'people': [0, 1, 3], 'source': 'Google Meet',
        'chapters': ['Incident timeline', 'Root cause and fix', 'Validation and ownership'],
        'overview': 'A double click submitted the same task twice in the prototype. The immediate fix is disabling submission while a request is pending and retaining form input on failure. Backend retry semantics need separate design.',
        'notes': 'Root cause: repeated client submissions, not a database cascade issue. Decision: protect pending submissions; do not deduplicate task text because identical tasks can be intentional.',
        'tasks': [(1, 'Disable task submission during pending requests and retain failed input'), (3, 'Verify duplicate-click and failed-request behavior in the task form')],
        'turns': [
            (3, 'Yesterday a pilot user created two identical action items by clicking save twice. Both requests succeeded. I reproduced the behavior with a slow connection in the prototype task form.'),
            (0, 'Did the backend create two rows from one request, or did it receive two separate requests? The fix depends on whether the duplication happened in persistence or at submission time.'),
            (1, 'The logs show two separate requests. Each transaction created one row correctly. The submit button stays enabled while the first request is pending, which allows the second click.'),
            (3, 'The user then deleted one duplicate and worried that the other would disappear too. Both rows had different identifiers, so deleting one did not affect the remaining task.'),
            (0, 'For the immediate fix, disable save during the pending request and show a progress label. We should not deduplicate by text because two similar tasks may be intentional.'),
            (1, 'I agree. Reliable network retries would need an idempotency contract, which is a separate design decision. For now the client should avoid automatically retrying a task creation request.'),
            (3, 'Please keep the entered text if the request fails. A disabled button alone is not sufficient if the user loses their work and has to type the entire action item again.'),
            (1, 'I will preserve form state on failure and re-enable save with a visible error. On success, the form will reset only after the API returns the created task identifier.'),
            (0, 'Daniel, verify double clicks on a slow connection and a simulated failed request. We should also confirm that the complete toggle updates the correct task after two similar tasks exist.'),
            (3, 'I will run those checks after the fix lands and record the results. We have a clear cause and follow-up plan. Thanks everyone; I will close this incident review.'),
        ],
    },
    {
        'title': 'Weekly product and engineering sync', 'date': '2026-10-07T09:30:00+00:00',
        'people': [0, 1, 2, 4], 'source': 'Microsoft Teams',
        'chapters': ['Delivery status', 'Remaining product questions', 'Next milestone'],
        'overview': 'The foundation is ready for integration review. Next work is the meetings library and transcript detail UI. The team prioritized search, persistent action-item completion, and realistic sample data before optional features.',
        'notes': 'Decision: validate the API client before building all screens. No authentication or real speech-to-text in this milestone. Demo walkthrough will cover search, review, task completion, and deletion.',
        'tasks': [(1, 'Connect the typed client to the meetings library'), (2, 'Prepare the transcript detail implementation checklist')],
        'turns': [
            (0, 'Let us do a quick weekly sync. The foundation is ready for integration review, and I want to confirm what we build next before we start adding more screens.'),
            (1, 'The backend has meeting CRUD, transcript retrieval, summaries, chapters, and action items. I want to validate the typed client against those endpoints before wiring every page to the API.'),
            (2, 'The next design milestone is the library and transcript detail view. We have enough direction for both, but I will prepare an implementation checklist for the playback and search interactions.'),
            (4, 'For the demo, can we include several realistic meetings rather than repeating the same conversation? That will make search and participant filters much easier to understand during evaluation.'),
            (0, 'Yes. Each sample needs a complete transcript, summary, chapters, and tasks with different owners. We should use short meetings that cover distinct topics so the data remains easy to review.'),
            (1, 'I will keep action-item completion persistent and validate speaker membership. The integration demo can search for a topic, open a meeting, complete a task, and reload to verify the change.'),
            (2, 'I also want to show deletion with a confirmation in the later UI. The library should update immediately after success, and the detail route should handle a meeting that no longer exists.'),
            (4, 'That walkthrough sounds clear. I will keep the demo script focused on those workflows. Authentication and real speech-to-text are outside this milestone, so they do not need demo time.'),
            (0, 'Then our next step is the library integration followed by the detail implementation. Optional exports and chat can wait until the required search and task workflows are verified end to end.'),
            (1, 'I will connect the library client next, and Maya will share the detail checklist. We will review progress on Friday. Thanks everyone; that wraps up the weekly sync.'),
        ],
    },
]
