"""initial normalized meeting schema"""
from alembic import op
import sqlalchemy as sa
revision = '1f63c5f77976'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('processing', 'completed', 'failed')"),
    sa.CheckConstraint('duration_seconds >= 0'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.create_index('ix_meetings_started_id', ['started_at', 'id'], unique=False)
        batch_op.create_index('ix_meetings_status', ['status'], unique=False)
        batch_op.create_index('ix_meetings_title', ['title'], unique=False)

    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participants_email'), ['email'], unique=True)

    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('start_seconds', sa.Integer(), nullable=False),
    sa.Column('end_seconds', sa.Integer(), nullable=False),
    sa.CheckConstraint('position >= 0'),
    sa.CheckConstraint('start_seconds >= 0 AND end_seconds > start_seconds'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'position')
    )
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.create_index('ix_chapters_meeting_time', ['meeting_id', 'start_seconds'], unique=False)

    op.create_table('meeting_participants',
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('meeting_id', 'participant_id')
    )
    with op.batch_alter_table('meeting_participants', schema=None) as batch_op:
        batch_op.create_index('ix_meeting_participants_participant', ['participant_id'], unique=False)

    op.create_table('summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('overview', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id')
    )
    op.create_table('action_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.CheckConstraint("status IN ('open', 'completed')"),
    sa.ForeignKeyConstraint(['meeting_id', 'assignee_id'], ['meeting_participants.meeting_id', 'meeting_participants.participant_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action_items', schema=None) as batch_op:
        batch_op.create_index('ix_action_items_assignee', ['assignee_id'], unique=False)
        batch_op.create_index('ix_action_items_meeting_status', ['meeting_id', 'status'], unique=False)

    op.create_table('transcript_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('speaker_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('start_seconds', sa.Integer(), nullable=False),
    sa.Column('end_seconds', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.CheckConstraint('position >= 0'),
    sa.CheckConstraint('start_seconds >= 0 AND end_seconds > start_seconds'),
    sa.ForeignKeyConstraint(['meeting_id', 'speaker_id'], ['meeting_participants.meeting_id', 'meeting_participants.participant_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'position')
    )
    with op.batch_alter_table('transcript_segments', schema=None) as batch_op:
        batch_op.create_index('ix_transcript_meeting_time', ['meeting_id', 'start_seconds'], unique=False)

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcript_segments', schema=None) as batch_op:
        batch_op.drop_index('ix_transcript_meeting_time')

    op.drop_table('transcript_segments')
    with op.batch_alter_table('action_items', schema=None) as batch_op:
        batch_op.drop_index('ix_action_items_meeting_status')
        batch_op.drop_index('ix_action_items_assignee')

    op.drop_table('action_items')
    op.drop_table('summaries')
    with op.batch_alter_table('meeting_participants', schema=None) as batch_op:
        batch_op.drop_index('ix_meeting_participants_participant')

    op.drop_table('meeting_participants')
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_index('ix_chapters_meeting_time')

    op.drop_table('chapters')
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participants_email'))

    op.drop_table('participants')
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_index('ix_meetings_title')
        batch_op.drop_index('ix_meetings_status')
        batch_op.drop_index('ix_meetings_started_id')

    op.drop_table('meetings')
    # ### end Alembic commands ###
